# Generated by Django 2.1.7 on 2019-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColourScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('green', 'GREEN'), ('metalic', 'METALIC'), ('black', 'BLACK'), ('dark', 'DARK'), ('classic', 'CLASSIC')], default='green', max_length=20)),
            ],
        ),
    ]
