# Generated by Django 2.1.7 on 2019-04-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylechange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colourscheme',
            old_name='colour',
            new_name='colourpicker',
        ),
    ]
