# Generated by Django 2.1.7 on 2019-04-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylechange', '0002_auto_20190406_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourscheme',
            name='colourpicker',
            field=models.CharField(choices=[('green', 'Green on Green'), ('steel', 'Default'), ('blue', 'Blue'), ('dark', 'Dark'), ('classic', 'Classic'), ('metalic', 'Metalic')], default='green', max_length=20),
        ),
    ]
