# Generated by Django 2.1.7 on 2019-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylechange', '0003_auto_20190423_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourscheme',
            name='colourpicker',
            field=models.CharField(choices=[('green', 'Green on Green'), ('steel', 'Default'), ('blue', 'Blue'), ('dark', 'Dark'), ('classic', 'Classic'), ('metalic', 'Metalic'), ('sunburst', 'Sunburst')], default='green', max_length=20),
        ),
    ]
