# Generated by Django 2.2.1 on 2019-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylechange', '0004_auto_20190511_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourscheme',
            name='colourpicker',
            field=models.CharField(choices=[('green', 'Green on Green'), ('blue', 'Blue'), ('night', 'Dark'), ('classic', 'Classic'), ('metalic', 'Metalic'), ('sunburst', 'Sunburst')], default='green', max_length=20),
        ),
    ]
