# Generated by Django 2.2.1 on 2019-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylechange', '0006_colourscheme_website_body_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_picker', models.CharField(choices=[('old_template', 'Vag Society'), ('new_template', 'Vag Society 2.0')], default='new_template', max_length=30)),
            ],
        ),
    ]
