# Generated by Django 2.2.1 on 2019-12-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylechange', '0007_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_picker',
            field=models.CharField(choices=[('old_template', 'Vag Society'), ('new_template', 'Vag Society 2.0')], default='new_template', max_length=30, verbose_name='Choose A Template'),
        ),
    ]
