# Generated by Django 2.2.1 on 2019-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecomments',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='imagecomments',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagecomments',
            name='content',
            field=models.TextField(verbose_name='New Comment'),
        ),
    ]
